### ISSUE TITLE
not recognized by heroku

### ISSUE THREAD

**Issue by gilbertlucas46** [dsebastien/modernWebDevGenerator#102]
![screenshot_1](https://cloud.githubusercontent.com/assets/5719346/14934494/353dce7a-0ee4-11e6-9ffb-3d4e1b31bae8.jpg)

**Comment by dsebastien** [comment]
I don't have any experience with Heroku so I don't know how to help you out.
One question: what happens if you copy the dist folder contents to a bare bones Web server (e.g., Apache or Nginx) or start a Web server using http-server, superstatic or a similar solution? Does the application work? If so, then it's really something about Heroku..

**Comment by gilbertlucas46** [comment]
i tried just pushing a subtree to heroku using this commang "git subtree push --prefix dist heroku master"
but its failing because heroku cant recognized what kind of build this is.

While in apache I'm receiving a Get error
![screenshot_1](https://cloud.githubusercontent.com/assets/5719346/14969676/3277e82e-10f6-11e6-9130-8d3c905211df.jpg)

**Comment by dsebastien** [comment]
Well the thing is that the build shouldn't matter to Heroku. The dist folder contains a fully static site; maybe this article could help you out: https://gist.github.com/wh1tney/2ad13aa5fbdd83f6a489

As for the bundle.min.js loading error, without more information I really can't help.

**Comment by gilbertlucas46** [comment]
Hi, I followed the instructions from the link you just gave me it works!, i can see the site. 
what I did is I point index.php to /dist  folder **<?php include_once("dist/index.html"); ?>**
but now the problem is it doesn't seem to find the assets **(css,js)**

Here's the link of my application from heroku for your reference
https://cheapytrippy-test.herokuapp.com/

![screenshot_7](https://cloud.githubusercontent.com/assets/5719346/15035438/8b6008f8-12b4-11e6-9e11-9f57ec0eadcd.png)

without ../
![screenshot_8](https://cloud.githubusercontent.com/assets/5719346/15035498/0b5eac6c-12b5-11e6-99d3-3d13d9e1bb4c.png)

**Comment by dsebastien** [comment]
Good news :)
For the bundles loading, the only thing that comes to my mind is that you might be using an older version of the generator/build and/or have generated your project before my most recent changes.

There were some issues that I did fix: https://github.com/dsebastien/modernWebDevGenerator/issues/94 & https://github.com/dsebastien/modernWebDevBuild/issues/105. I guess these might be related (?).

**Comment by gilbertlucas46** [comment]
wow nice ill check it today, then I'll let you know. thanks for help!

By the way I've been using this repo because I needed angular with it
https://github.com/dsebastien/modernWebDevGenerator
and i look at the package.json and theres no gulp-wait included

can i just add this inside gulp/task?
https://github.com/dsebastien/modernWebDevBuild/blob/master/src/gulp/tasks/serve-dist.js#L51
  **serve-dist.js**

**Comment by gilbertlucas46** [comment]
Hi so i figured out whats going wrong, turns out i  need to add **dist**/ in every path of my assets.
<link rel="stylesheet" href="dist/vendor.min.css">
<link rel="stylesheet" href="dist/bundle.min.css">

<script src="dist/bundle.min.js"></script>

![screenshot_1](https://cloud.githubusercontent.com/assets/5719346/15062736/a9222508-1375-11e6-8dd8-1b4986b50193.png)

here's the new heroku app I made
https://cheapytrippy.herokuapp.com/

**Comment by dsebastien** [comment]
Meaning that your index.html page is not within the dist folder?
If so then it's normal that it didn't work. The idea of the dist folder is that it contains a self-contained (sic) version of the app.

**Comment by gilbertlucas46** [comment]
Nope it is inside the dist folder
