### ISSUE TITLE
Link on Yeoman generators page is wrong

### ISSUE THREAD

**Issue by simonsheridan** [dsebastien/modernWebDevGenerator#65]
Go to http://yeoman.io/generators/ and search 'angular 2' or whatever, find the entry for this project 'modern-web-dev'.  the link should link to this github page, https://github.com/dsebastien/modernWebDevGenerator, but instead links to https://www.dsebastien.net/

**Comment by dsebastien** [comment]
@simonsheridan hey, good catch. The homepage is not set correctly (it's my site); I probably copy pasted that when I created the project :)

**Comment by simonsheridan** [comment]
@dsebastien Yeah no problem!  I'm excited to check out your generator
