### ISSUE TITLE
Components scss files are not exported

### ISSUE THREAD

**Issue by JanOschii** [dsebastien/modernWebDevGenerator#67]
If I build a project with "gulp" or start the server with "npm run serve" then the components scss files are not part of the project.I created the files like documented in the readme:

```
components\
    login\
        login.scss
        login.model.ts
        login.controller.ts
        login.template.html
        ...
```

I tried to name the scss files with and without a leading underscore: 
_login.scss and login.scss

The controller and templates are exported, but not the css files

Maybe I am the only one with this problem, cause of the issue #66

**Comment by JanOschii** [comment]
If i use "npm run serve", then its exported. So I think, that is a not a real issue.
Sorry.

**Comment by dsebastien** [comment]
Issues that resolve themselves are always nice :)

Normally all sass partials should be transpiled
- during serve (npm run serve)
  - files you create while the server is running might not be taken into account though
- during the dist build creation (npm run build). In that case:
  - two bundles will be created (main.css & vendor.css) which will contain all you were importing in
