### ISSUE TITLE
build project error win10_x64

### ISSUE THREAD

**Issue by omni360** [dsebastien/modernWebDevGenerator#92]
@dsebastien hi, the generator is greet.I love it .but I fonund an issue when I use it on win10_x64, finished run npm setup. 
please see bellow the picture.
![capture](https://cloud.githubusercontent.com/assets/2369679/13370072/31efc4f8-dd39-11e5-8e36-7a85532ff369.PNG)

**Comment by dsebastien** [comment]
Hi @omni360 I'll take a look at it.

**Comment by dsebastien** [comment]
Actually I can't reproduce this as RxJS is not used in the example pages provided by the generator.
If you want you can take a look at that project: https://github.com/dsebastien/midnightLightV2
There I use Angular 2 beta 7 along with RxJS and it works.
